/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package operadores;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author santa
 */
public class Operaciones extends javax.swing.JFrame {

    /**
     * Creates new form Operaciones
     */
    public Operaciones() {
        initComponents();
        this.setTitle("Calculadora CustomSoft");
        Image img = Toolkit.getDefaultToolkit().createImage(getClass().getResource("/Imagenes/logo02.jpg"));
        this.setIconImage(img);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblOperaciones = new javax.swing.JLabel();
        lblNumero01 = new javax.swing.JLabel();
        lblNumero02 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        txtNum01 = new javax.swing.JTextField();
        txtNum02 = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        lblLogo = new javax.swing.JLabel();
        btnSuma = new javax.swing.JButton();
        btnRaiz = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btnMultiplicacion = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.SystemColor.inactiveCaption);
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(600, 400));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 400));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOperaciones.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lblOperaciones.setForeground(new java.awt.Color(102, 102, 102));
        lblOperaciones.setText("Operaciones con numeros");
        lblOperaciones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lblOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 290, -1));

        lblNumero01.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lblNumero01.setForeground(new java.awt.Color(102, 102, 102));
        lblNumero01.setText("1er Numero");
        lblNumero01.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lblNumero01, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 140, -1));

        lblNumero02.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lblNumero02.setForeground(new java.awt.Color(102, 102, 102));
        lblNumero02.setText("2do Numero");
        lblNumero02.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lblNumero02, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 140, -1));

        lblTotal.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(102, 102, 102));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotal.setText("Total");
        lblTotal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 140, 30));

        txtNum01.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        txtNum01.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNum01.setToolTipText("");
        txtNum01.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNum01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNum01ActionPerformed(evt);
            }
        });
        jPanel1.add(txtNum01, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 100, 30));

        txtNum02.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        txtNum02.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNum02.setToolTipText("");
        txtNum02.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtNum02, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 100, 30));

        txtTotal.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotal.setToolTipText("");
        txtTotal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 220, -1));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo02.jpg"))); // NOI18N
        jPanel1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 240, 100));

        btnSuma.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnSuma.setForeground(new java.awt.Color(102, 102, 102));
        btnSuma.setText("Sumar");
        btnSuma.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 110, 50));

        btnRaiz.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnRaiz.setForeground(new java.awt.Color(102, 102, 102));
        btnRaiz.setText("Raiz Cuadrada ");
        btnRaiz.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaizActionPerformed(evt);
            }
        });
        jPanel1.add(btnRaiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 480, 50));

        btnResta.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnResta.setForeground(new java.awt.Color(102, 102, 102));
        btnResta.setText("Resta");
        btnResta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });
        jPanel1.add(btnResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 120, 50));

        btnMultiplicacion.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btnMultiplicacion.setForeground(new java.awt.Color(102, 102, 102));
        btnMultiplicacion.setText("Multiplicacion");
        btnMultiplicacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicacionActionPerformed(evt);
            }
        });
        jPanel1.add(btnMultiplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 110, 50));

        btnDivision.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnDivision.setForeground(new java.awt.Color(102, 102, 102));
        btnDivision.setText("Division");
        btnDivision.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });
        jPanel1.add(btnDivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 110, 50));

        btnBorrar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(102, 102, 102));
        btnBorrar.setText("Borrar");
        btnBorrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 60, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNum01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNum01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNum01ActionPerformed

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed

        int Num1, Num2, Total;

        Num1 = Integer.parseInt(txtNum01.getText());
        Num2 = Integer.parseInt(txtNum02.getText());

        Total = Num1 + Num2;

        txtTotal.setText(String.valueOf(Total));

    }//GEN-LAST:event_btnSumaActionPerformed

    private void btnRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaizActionPerformed

        int Num1, Num2, Total, Total1;
        double raiz, raiz1;

        Num1 = Integer.parseInt(txtNum01.getText());
        Num2 = Integer.parseInt(txtNum02.getText());

        Total = Num1 + Num2;

        if (Total < 0) {
            Total1 = (-1) * Total;
            raiz1 = Math.sqrt(Total1);
            txtTotal.setText("-" + raiz1 + "i");
        } else {
            raiz = Math.sqrt(Total);
            txtTotal.setText(String.valueOf(raiz));
        }
    }//GEN-LAST:event_btnRaizActionPerformed

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
        int Num1, Num2, Total;

        Num1 = Integer.parseInt(txtNum01.getText());
        Num2 = Integer.parseInt(txtNum02.getText());

        Total = Num1 - Num2;

        txtTotal.setText(String.valueOf(Total));
    }//GEN-LAST:event_btnRestaActionPerformed

    private void btnMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicacionActionPerformed
        int Num1, Num2, Total;

        Num1 = Integer.parseInt(txtNum01.getText());
        Num2 = Integer.parseInt(txtNum02.getText());

        Total = Num1 * Num2;

        txtTotal.setText(String.valueOf(Total));
    }//GEN-LAST:event_btnMultiplicacionActionPerformed

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed
        int Num1, Num2, Total;

        Num1 = Integer.parseInt(txtNum01.getText());
        Num2 = Integer.parseInt(txtNum02.getText());
        if (Num2>=0){
        txtTotal.setText("El segundo numero debe ser mayor a cero(0)");
        }else{
        Total = Num1 / Num2;
        txtTotal.setText(String.valueOf(Total));
        }
        
    }//GEN-LAST:event_btnDivisionActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        txtTotal.setText("");
        txtNum01.setText("");
        txtNum02.setText("");
    }//GEN-LAST:event_btnBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Operaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnMultiplicacion;
    private javax.swing.JButton btnRaiz;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSuma;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNumero01;
    private javax.swing.JLabel lblNumero02;
    private javax.swing.JLabel lblOperaciones;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField txtNum01;
    private javax.swing.JTextField txtNum02;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
